### ISSUE TITLE
when i use `Flush` function not works on  Linux(Ubuntu)

### ISSUE THREAD

**Issue by xujiajun** [grandecola/mmap#14]
@mangalaman93 @ashish-goswami 

hi, it's a nice package. 
when i use `Flush` function  works on Mac OS X  ,but not work on  Linux(Ubuntu). it will report the error :  `invalid argument`

```
	err:=m.Flush(syscall.SYS_SYNC)
	if err!=nil {  
		t.Error(err) // L90
	}
```

error detail 

 ```
FAIL: TestReadWrite (0.00s)
    mmap_test.go:90: invalid argument
FAIL
exit status 1
FAIL	github.com/grandecola/mmap	0.003s
 ```
Cloud you give me some advices?  thanks ;)

**Comment by mangalaman93** [comment]
Use `syscall.MS_SYNC` instead.
